dbMemo "SQL" ="DELETE QueryInvoicesLastDate.Customer_ID, QueryInvoicesLastDate.Date, QueryInvoi"
    "cesLastDate.Document_Number, QueryInvoicesLastDate.Customer_reference, QueryInvo"
    "icesLastDate.Type, QueryInvoicesLastDate.Amount, QueryInvoicesLastDate.Overdue_D"
    "ate, QueryInvoicesLastDate.Currency, QueryInvoicesLastDate.Query, QueryInvoicesL"
    "astDate.mEMO, QueryInvoicesPreviousDate.Tbl_Invoices.Update_date\015\012FROM Que"
    "ryInvoicesPreviousDate RIGHT JOIN QueryInvoicesLastDate ON (QueryInvoicesPreviou"
    "sDate.Customer_ID=QueryInvoicesLastDate.Customer_ID) AND (QueryInvoicesPreviousD"
    "ate.Date=QueryInvoicesLastDate.Date) AND (QueryInvoicesPreviousDate.Document_Num"
    "ber=QueryInvoicesLastDate.Document_Number)\015\012WHERE (((QueryInvoicesLastDate"
    ".Document_Number)<>\" \") AND ((QueryInvoicesPreviousDate.Tbl_Invoices.Update_da"
    "te) Is Null));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "UseTransaction" ="0"
dbBoolean "FailOnError" ="0"
dbByte "Orientation" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
    Begin
        dbText "Name" ="QueryInvoicesPreviousDate.Tbl_Invoices.Update_date"
        dbInteger "ColumnWidth" ="4800"
        dbBoolean "ColumnHidden" ="0"
        dbLong "AggregateType" ="-1"
    End
End
