CREATE TABLE [CreditCheckFailureTXTFileAmended] (
  [Hold Type] VARCHAR (255),
  [Hold Name] VARCHAR (255),
  [Date Hold Applied] DATETIME,
  [Hold Until Date] VARCHAR (255),
  [Hold Comments] VARCHAR (255),
  [Release Reason] VARCHAR (255),
  [Released By] VARCHAR (255),
  [Release Comment] VARCHAR (255),
  [Release Date] VARCHAR (255),
  [Object Type] VARCHAR (255),
  [Sub-Region] VARCHAR (255),
  [Country] VARCHAR (255),
  [Organization Name] VARCHAR (255),
  [Sales Channel] VARCHAR (255),
  [Customer Name] VARCHAR (255),
  [Customer Number] LONG,
  [Account Specialist] VARCHAR (255),
  [Ship To Country] VARCHAR (255),
  [Bill To Country] VARCHAR (255),
  [Location] VARCHAR (255),
  [Logitech Item Number] VARCHAR (255),
  [Item Description] VARCHAR (255),
  [Marketing Name] VARCHAR (255),
  [Customer Promotional Reference] LONG,
  [Promotional Reference] LONG,
  [Promotional Reference Required] VARCHAR (255),
  [Modifier Name] VARCHAR (255),
  [Modifier Line Number] LONG,
  [Price List Name] VARCHAR (255),
  [Customer Price] VARCHAR (255),
  [List Price] DOUBLE,
  [Special Price] DOUBLE,
  [Initial Promotional quantity] VARCHAR (255),
  [Remaining Promotional quantity] LONG,
  [Requested Quantity] LONG,
  [Currency Code] VARCHAR (255),
  [Amount] DOUBLE,
  [Order Number] LONG,
  [Order Line Number] DOUBLE,
  [Order Date] DATETIME,
  [Requested Date] DATETIME,
  [Schedule Date] DATETIME,
  [Active Hold] VARCHAR (255),
  [Open Line] VARCHAR (255),
  [Line Status] VARCHAR (255),
  [Hold Criteria] VARCHAR (255),
  [Tax Code] VARCHAR (255)
)
