CREATE TABLE [Paste Errors] (
  [Tbl_Customers_Customer_code] LONG,
  [Tbl_Customers1_Customer_code] LONG,
  [Credit_controller] VARCHAR (255),
  [Name] VARCHAR (255),
  [Address] VARCHAR (255),
  [Address2] VARCHAR (255),
  [Address3] VARCHAR (255),
  [Address4] VARCHAR (255),
  [Address5] VARCHAR (255),
  [Country] VARCHAR (255),
  [Update_date] DATETIME,
  [OWN_company] VARCHAR (255),
  [OWN_bank_details1] VARCHAR (255),
  [OWN_bank_details2] VARCHAR (255),
  [OWN_bank_details3] VARCHAR (255),
  [OWN_bank_details4] VARCHAR (255),
  [NextAppointment] DATETIME,
  [Email] VARCHAR (255),
  [DA TOGLIEREEEEEEEE TextEmail] LONGTEXT,
  [ccEmail] VARCHAR (255),
  [StatusDate] DATETIME,
  [ToSendStatement] BIT,
  [Index] CURRENCY,
  [Note] LONGTEXT,
  [ToSendRequestRelease] BIT,
  [TotalInsurance] CURRENCY,
  [StatementForm] UNSIGNED BYTE,
  [RetailOEM] VARCHAR (255),
  [ToReleaseOrder] BIT,
  [Status] LONG,
  [Timezone] LONG,
  [Language] LONG,
  [ContactNames] VARCHAR (255),
  [DSO] LONG,
  [EmailCode] LONG,
  [Area] LONG,
  [LastStatementSent] DATETIME,
  [FacturaNumberToBePrinted] BIT,
  [PullTicketNumberToBePrinted] BIT,
  [OriginalInvoiceAmountToBePrinted] BIT,
  [HighestExposure] CURRENCY,
  [ReleaseNotes] LONGTEXT,
  [MonthlyTargetInMainCurrency] CURRENCY
)
