CREATE TABLE [Tbl_LOGICollectionsManagementReport] (
  [ID] AUTOINCREMENT,
  [Region] VARCHAR (255),
  [Country] VARCHAR (255),
  [Customer Number] LONG,
  [Customer Name] VARCHAR (255),
  [Group] VARCHAR (255),
  [Sales Channel] VARCHAR (255),
  [Oracle CL] VARCHAR (255),
  [Trade Ins CL] CURRENCY,
  [Trade Insurance] VARCHAR (255),
  [Total AR] VARCHAR (255),
  [Securities] VARCHAR (255),
  [Net Exposure] VARCHAR (255),
  [Current AR] VARCHAR (255),
  [Total Overdue] VARCHAR (255),
  [Total Over 90 days] VARCHAR (255),
  [Total Over 180 days] VARCHAR (255),
  [Forward Balance (in 2 week)] VARCHAR (255),
  [CL % USED] VARCHAR (255),
  [STATUS] VARCHAR (255),
  [Risk] VARCHAR (255),
  [Amount Scheduled for this Quarter] VARCHAR (255),
  [Collector] VARCHAR (255)
)
