CREATE TABLE [Tbl_Timezones] (
  [ID1] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [ID] VARCHAR (2),
  [COUNTRY] VARCHAR (255),
  [GMT_HOUR] DOUBLE,
  [PERIOD LEGAL HOUR] VARCHAR (255),
  [PERIODLEGALHOURCODE] VARCHAR (255),
  [LEGAL HOUR] DOUBLE,
  [s_ColLineage] LONGBINARY,
  [s_Generation] LONG,
  [s_GUID] GUID CONSTRAINT [s_GUID] UNIQUE,
  [s_Lineage] LONGBINARY
)
