VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICustomerHeaderSupport"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public Function Populate(aCustomerID As String) As Scripting.Dictionary

End Function

Public Function GetDictionary() As Scripting.Dictionary

End Function
