VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWhoPaidYesterdaySupport"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit
Function GetLastInvoiceImportDate(SQL As String) As Date

End Function

Function OneBeforeLastInvoiceImportDate(SQL As String) As Date

End Function

Function UpdateQueryInvoicesLastDate(SQL As String) As Boolean

End Function
Function UpdateQueryInvoicesPreviousDate(SQL As String) As Boolean

End Function
