VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWhoPaidYesterday"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Compare Database
Option Explicit

Public Function Inject(ByRef aInject As IWhoPaidYesterdaySupport) As Boolean
End Function


Public Function GetRecordSourceSQL() As String

End Function

Public Function LastInvoiceImportDateSQL() As String

End Function

Public Function QueryInvoicesLastDateSQL() As String

End Function

Public Function BeforeLastInvoiceImportDateSQL() As String

End Function
Public Function UpdateSecondaryQueries() As Boolean

End Function
