dbMemo "SQL" ="SELECT QueryInvoicesPreviousDate.*, Tbl_queries.Query\015\012FROM (QueryInvoices"
    "PreviousDate LEFT JOIN QueryInvoicesLastDate ON (QueryInvoicesPreviousDate.Docum"
    "ent_Number=QueryInvoicesLastDate.Document_Number) AND (QueryInvoicesPreviousDate"
    ".Date=QueryInvoicesLastDate.Date) AND (QueryInvoicesPreviousDate.Customer_ID=Que"
    "ryInvoicesLastDate.Customer_ID)) LEFT JOIN Tbl_queries ON QueryInvoicesPreviousD"
    "ate.Query=Tbl_queries.ID\015\012WHERE (((QueryInvoicesLastDate.Date) Is Null));\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
Begin
End
