SELECT
  Tbl_Customers.Name AS Expr1,
  Tbl_Customers.Address AS Expr2,
  Tbl_Customers.Address2 AS Expr3,
  Tbl_Customers.Address3 AS Expr4,
  Tbl_Customers.Address4 AS Expr5,
  "city" AS Expr1,
  Tbl_Customers.Country AS Expr6,
  Tbl_Customers.NextAppointment AS Expr7,
  Tbl_Customers.StatusDate AS Expr8,
  Tbl_Customers.Index AS Expr9,
  Tbl_Customers.Note AS Expr10,
  Tbl_Customers.TotalInsurance AS Expr11,
  Tbl_Customers.Status AS Expr12,
  Tbl_Customers.Timezone AS Expr13,
  Tbl_Customers.Language AS Expr14,
  Tbl_Customers.DSO AS Expr15,
  Tbl_Customers.Area AS Expr16,
  Tbl_Customers.LastStatementSent AS Expr17,
  "sales channel" AS Expr2,
  "active" AS Expr3,
  "total CL" AS Expr4,
  "sales person" AS Expr5,
  Tbl_Customers.Customer_code AS Expr18,
  "postal code" AS Expr6,
  "county" AS Expr7,
  "group code" AS Expr8,
  "collection_category" AS Expr9,
  "collection_step" AS Expr10
FROM
  Tbl_Customers;
