CREATE TABLE [Tbl_credit_check_failures] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] UNIQUE,
  [Hold Type] VARCHAR (255),
  [Hold Name] VARCHAR (255),
  [Date Hold Applied] DATETIME,
  [Hold Until Date] DATETIME,
  [Hold Comments] VARCHAR (255),
  [Sub-Region] VARCHAR (255),
  [Country] VARCHAR (255),
  [Customer Name] VARCHAR (255),
  [Customer Number] DOUBLE,
  [Account Specialist] VARCHAR (255),
  [Logitech Item Number] VARCHAR (255),
  [Item Description] VARCHAR (255),
  [List Price] CURRENCY,
  [Requested Quantity] DOUBLE,
  [Currency Code] VARCHAR (255),
  [Amount] CURRENCY,
  [Order Number] DOUBLE,
  [Order Line Number] VARCHAR (255),
  [Order Date] DATETIME,
  [Requested Date] DATETIME,
  [Schedule Date] DATETIME,
  [Active Hold] VARCHAR (255),
  [Open Line] VARCHAR (255),
  [Line Status] VARCHAR (255),
  [Hold Criteria] VARCHAR (255),
  [Tax Code] VARCHAR (255),
  [Released] BIT
)
