CREATE TABLE [TblGeneral] (
  [ID] AUTOINCREMENT CONSTRAINT [ID] UNIQUE,
  [PathStatemets] VARCHAR (255),
  [LastUpdate] DATETIME,
  [PathLogo] VARCHAR (150),
  [PathQueryFile] VARCHAR (200),
  [PathExcelDirectory] VARCHAR (200),
  [PathReleases] VARCHAR (50),
  [Credit_Manager] VARCHAR (100),
  [Credit_Supervisor] VARCHAR (150),
  [Update_CL+1] DATETIME,
  [Update_CL+8] DATETIME,
  [Update_Customers_Failing] DATETIME,
  [CreditManagerEmail] VARCHAR (150),
  [SupervisorEmail] VARCHAR (150),
  [GNT] LONG,
  [ImportingProcess] BIT,
  [PathChargebackFile] VARCHAR (255),
  [PathWordDirectory] VARCHAR (255),
  [DefaultTemplate] LONG,
  [DefaultTemplateInWhoPaidYesterday] LONG,
  [DefaultTemplateInForwardAging] LONG,
  [ToBeSentCLto] VARCHAR (250),
  [CLHorizonDateLimit] DATETIME,
  [Cash Target] CURRENCY,
  [PathInvoiceAttachments] VARCHAR (255),
  [CollectionManagementReportTXTFileHeader] LONGTEXT,
  [MaxOldStatementInArchive] LONG,
  [Sendusing] VARCHAR (255),
  [SMTPServer] VARCHAR (255),
  [SMTPServerport] VARCHAR (255),
  [smtpauthenticate] VARCHAR (255),
  [SMTPusessl] BIT,
  [SMTPconnectiontimeout] VARCHAR (255),
  [MainCurrency] VARCHAR (255),
  [CreditLimitCheckFailureTXTFileHeader] LONGTEXT,
  [Area] VARCHAR (255),
  [ToBeSentCashTargetTo] LONGTEXT,
  [CashTargetReportSchedule] UNSIGNED BYTE,
  [LastCashTargetSent] DATETIME,
  [PathImages] VARCHAR (255),
  [CashCollectedSecondGroupDays] LONG,
  [ToBeSentCashTargetToSecondGroup] LONGTEXT,
  [PathTemplates] VARCHAR (255),
  [GitLatestReleaseNumberFile] VARCHAR (255),
  [LocalLatestReleaseNumberFile] VARCHAR (255),
  [GitUpdatedApp] VARCHAR (255),
  [PathDB] VARCHAR (255)
)
